# Generated by Django 5.2.7 on 2025-11-04 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ceb821c-9bb8-401f-a8fb-7929ad96a455'), primary_key=True, serialize=False),
        ),
    ]
