# Generated by Django 5.2.7 on 2025-11-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('jti', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Уникальный id токена')),
                ('device_id', models.CharField(max_length=40, verbose_name='Уникальный id устройства сгенерированный на клиенте и хранящийся в cookie')),
                ('ip_address', models.CharField(max_length=15, verbose_name='Ip адрес устройства')),
                ('user_agent', models.CharField(max_length=100, verbose_name='Информация о браузере клиента')),
            ],
        ),
    ]
