# Generated by Django 5.2.7 on 2025-11-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_refreshtoken_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='device_id',
            field=models.CharField(max_length=40, verbose_name='Уникальный id устройства сгенерированный на клиенте и хранящийся в cookie'),
        ),
    ]
