# Generated by Django 5.2.7 on 2025-12-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_refreshtoken_device_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
