# Generated by Django 4.2 on 2025-08-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
                ('color', models.CharField(max_length=40, verbose_name='Цвет в формате rgb или rgba, который будет отображаться на статистике')),
                ('is_custom', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Категории задач',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=290, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание задачи')),
                ('order', models.IntegerField(verbose_name='Порядок задачи в списке')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Крайний срок выполнения задачи')),
                ('planned_time', models.DurationField(verbose_name='Время, запланированное на процесс выполнения задачи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.category', verbose_name='Категория, к которой относится задача')),
            ],
            options={
                'verbose_name': 'Задачи, которые пользователи ставят себе',
            },
        ),
    ]
