# Generated by Django 5.2.7 on 2025-12-23 18:22

import task.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_time',
            field=models.DurationField(validators=[task.validators.duration_validator], verbose_name='Время, запланированное на процесс выполнения задачи'),
        ),
    ]
