# Generated by Django 4.2 on 2025-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=290, verbose_name='Название задачи')),
                ('planned_time', models.DurationField(verbose_name='Время, которое было изначально запланировано на процесс выполнения задачи')),
                ('execution_time', models.DurationField(verbose_name='Время, которое реально потребовалось на выполнение задачи')),
                ('execution_date', models.DateField(auto_now_add=True, verbose_name='День, в который была выполнена задача')),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Успешно выполнена вовремя'), ('OUT_OF_DEADLINE', 'Выполнена с опозданием'), ('FAILED', 'Провалена')], max_length=50, verbose_name='Статус, к примеру, была задача выполнена или провалена')),
            ],
            options={
                'verbose_name': 'История выполненных и проваленных задач. Одна строка - одна задача.',
            },
        ),
    ]
