# Generated by Django 4.2 on 2025-10-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedHistoryStatistics',
            fields=[
                ('key', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Уникальный ключ по которому можно получить историю')),
                ('history_statistics', models.JSONField(verbose_name='Сохраненная история пользователя по определенному промежутку времени')),
            ],
        ),
    ]
