# Generated by Django 4.2 on 2025-10-13 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0004_sharedhistorystatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedhistorystatistics',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, сохранивший статистику'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharedhistorystatistics',
            name='history_statistics',
            field=models.JSONField(verbose_name='Сохраненная история пользователя по определенному промежутку времени'),
        ),
    ]
