# Generated by Django 4.2 on 2025-10-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_sharedhistorystatistics_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedhistorystatistics',
            name='from_date',
            field=models.DateField(null=True, verbose_name='Дата, начиная с которой будет показана история'),
        ),
        migrations.AddField(
            model_name='sharedhistorystatistics',
            name='to_date',
            field=models.DateField(null=True, verbose_name='Крайняя дата, по которую будет показана показана история'),
        ),
    ]
