# Generated by Django 4.2 on 2025-10-16 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('history', '0006_sharedhistorystatistics_from_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharedHistoryStatistics',
            new_name='SharedHistory',
        ),
        migrations.AlterModelOptions(
            name='sharedhistory',
            options={'verbose_name': 'Закэшированная в базе данных история пользователя по определенному отрезку времени чтобы сохранить ее в быстром доступе и поделиться с другими пользователями'},
        ),
    ]
