# Generated by Django 5.2.7 on 2025-11-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_rename_sharedhistorystatistics_sharedhistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': '\n            История выполненных и проваленных задач. Одна строка - одна задача.\n        '},
        ),
        migrations.AlterModelOptions(
            name='sharedhistory',
            options={'verbose_name': '\n        Закэшированная в базе данных история пользователя по определенному отрезку времени,\n        чтобы сохранить ее в быстром доступе и поделиться с другими пользователями\n        '},
        ),
    ]
