# Generated by Django 5.2.7 on 2026-01-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_alter_history_options_alter_sharedhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='planned_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Изначальный дедлайн задачи, если он был установлен'),
        ),
    ]
