# Generated by Django 5.2.7 on 2025-12-23 18:22

import task.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_alter_history_options_alter_sharedhistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='execution_time',
            field=models.DurationField(validators=[task.validators.duration_validator], verbose_name='Время, которое реально потребовалось на выполнение задачи'),
        ),
        migrations.AlterField(
            model_name='history',
            name='planned_time',
            field=models.DurationField(validators=[task.validators.duration_validator], verbose_name='Время, которое было изначально запланировано на процесс выполнения задачи'),
        ),
    ]
